import { PrismaClient } from "@prisma/client";
import { hexToLab } from "../../lib/paint-hub/color";

type PaintInput = {
  slug: string;
  name: string;
  hex: string;
  finish: string;
  category: string;
  range: string;
};

type BrandInput = {
  slug: string;
  name: string;
  website: string;
  paints: PaintInput[];
};

const BRANDS: BrandInput[] = [
  {
    slug: "citadel",
    name: "Citadel",
    website: "https://www.games-workshop.com",
    paints: [
      // Base
      { slug: "abaddon-black", name: "Abaddon Black", hex: "#231F20", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "mephiston-red", name: "Mephiston Red", hex: "#8C1515", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "macragge-blue", name: "Macragge Blue", hex: "#0D407F", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "caliban-green", name: "Caliban Green", hex: "#1A4A2E", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "averland-sunset", name: "Averland Sunset", hex: "#EFA120", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "zandri-dust", name: "Zandri Dust", hex: "#B5A96A", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "mechanicus-standard-grey", name: "Mechanicus Standard Grey", hex: "#595959", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "retributor-armour", name: "Retributor Armour", hex: "#B5933A", finish: "METALLIC", category: "BASE", range: "Base" },
      { slug: "corax-white", name: "Corax White", hex: "#E8E8E8", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "celestra-grey", name: "Celestra Grey", hex: "#9EAFA4", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "bugmans-glow", name: "Bugman's Glow", hex: "#7C4035", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "rakarth-flesh", name: "Rakarth Flesh", hex: "#B8A89A", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "jokaero-orange", name: "Jokaero Orange", hex: "#D6501A", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "screamer-pink", name: "Screamer Pink", hex: "#9C2A5C", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "naggaroth-night", name: "Naggaroth Night", hex: "#3D2B5E", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "kantor-blue", name: "Kantor Blue", hex: "#0B2D5F", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "incubi-darkness", name: "Incubi Darkness", hex: "#1C4A45", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "rhinox-hide", name: "Rhinox Hide", hex: "#4A2B1C", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "mournfang-brown", name: "Mournfang Brown", hex: "#6B2E15", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "steel-legion-drab", name: "Steel Legion Drab", hex: "#7A6E48", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "death-world-forest", name: "Death World Forest", hex: "#5C6B3D", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "grey-seer", name: "Grey Seer", hex: "#C8C8C8", finish: "MATTE", category: "BASE", range: "Base" },
      { slug: "wraithbone", name: "Wraithbone", hex: "#E8DCBE", finish: "MATTE", category: "BASE", range: "Base" },
      // Shade
      { slug: "nuln-oil", name: "Nuln Oil", hex: "#282828", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "agrax-earthshade", name: "Agrax Earthshade", hex: "#3D2B15", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "reikland-fleshshade", name: "Reikland Fleshshade", hex: "#A0542A", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "druchii-violet", name: "Druchii Violet", hex: "#5A3070", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "biel-tan-green", name: "Biel-Tan Green", hex: "#2D5A30", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "carroburg-crimson", name: "Carroburg Crimson", hex: "#6B1A2A", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "seraphim-sepia", name: "Seraphim Sepia", hex: "#8C6020", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "coelia-greenshade", name: "Coelia Greenshade", hex: "#285040", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "drakenhof-nightshade", name: "Drakenhof Nightshade", hex: "#1A2A5E", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "fuegan-orange", name: "Fuegan Orange", hex: "#8C3A10", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "athonian-camoshade", name: "Athonian Camoshade", hex: "#4A5A28", finish: "SATIN", category: "SHADE", range: "Shade" },
      { slug: "casandora-yellow", name: "Casandora Yellow", hex: "#C87A00", finish: "SATIN", category: "SHADE", range: "Shade" },
      // Layer
      { slug: "evil-sunz-scarlet", name: "Evil Sunz Scarlet", hex: "#C42024", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "wild-rider-red", name: "Wild Rider Red", hex: "#E03A18", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "skarsnik-green", name: "Skarsnik Green", hex: "#4E8C50", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "loren-forest", name: "Loren Forest", hex: "#3C6E3C", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "altdorf-guard-blue", name: "Altdorf Guard Blue", hex: "#2A4A90", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "calgar-blue", name: "Calgar Blue", hex: "#3A5FAA", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "ulthuan-grey", name: "Ulthuan Grey", hex: "#C8D8D8", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "ushabti-bone", name: "Ushabti Bone", hex: "#C8B878", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "screaming-skull", name: "Screaming Skull", hex: "#D8C890", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "auric-armour-gold", name: "Auric Armour Gold", hex: "#C89820", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "runefang-steel", name: "Runefang Steel", hex: "#C0C8D0", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "stormhost-silver", name: "Stormhost Silver", hex: "#D8E0E8", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "liberator-gold", name: "Liberator Gold", hex: "#B8902A", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "kabalite-green", name: "Kabalite Green", hex: "#288050", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "sybarite-green", name: "Sybarite Green", hex: "#38A862", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "xereus-purple", name: "Xereus Purple", hex: "#5A2878", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "genestealer-purple", name: "Genestealer Purple", hex: "#7A40A0", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "troll-slayer-orange", name: "Troll Slayer Orange", hex: "#E05010", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "flash-gitz-yellow", name: "Flash Gitz Yellow", hex: "#F0C800", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "yriel-yellow", name: "Yriel Yellow", hex: "#F0A800", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "dawnstone", name: "Dawnstone", hex: "#808080", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "administratum-grey", name: "Administratum Grey", hex: "#A0A8A8", finish: "MATTE", category: "LAYER", range: "Layer" },
      { slug: "white-scar", name: "White Scar", hex: "#F8F8F8", finish: "MATTE", category: "LAYER", range: "Layer" },
      // Contrast
      { slug: "black-templar", name: "Black Templar", hex: "#1A1A1A", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "skeleton-horde", name: "Skeleton Horde", hex: "#C8A840", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "nazdreg-yellow", name: "Nazdreg Yellow", hex: "#D89010", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "gryph-charger-grey", name: "Gryph-charger Grey", hex: "#6A7A88", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "magos-purple", name: "Magos Purple", hex: "#502870", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "talassar-blue", name: "Talassar Blue", hex: "#1A3870", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "militarum-green", name: "Militarum Green", hex: "#3A5830", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "gore-grunta-fur", name: "Gore-grunta Fur", hex: "#7A4020", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "blood-angels-red", name: "Blood Angels Red", hex: "#901010", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "ultramarines-blue", name: "Ultramarines Blue", hex: "#0A2890", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "ork-flesh", name: "Ork Flesh", hex: "#406030", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "cygor-brown", name: "Cygor Brown", hex: "#502010", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      // Technical
      { slug: "nihilakh-oxide", name: "Nihilakh Oxide", hex: "#70B0A0", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "typhus-corrosion", name: "Typhus Corrosion", hex: "#3A3020", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "blood-for-the-blood-god", name: "Blood for the Blood God", hex: "#800010", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "ardcoat", name: "Ardcoat", hex: "#F0F0F0", finish: "SATIN", category: "TECHNICAL", range: "Technical" },
      { slug: "agrellan-earth", name: "Agrellan Earth", hex: "#9A8060", finish: "MATTE", category: "TECHNICAL", range: "Technical" },
      // Dry
      { slug: "praxeti-white", name: "Praxeti White", hex: "#F0F0F0", finish: "MATTE", category: "DRY", range: "Dry" },
      { slug: "longbeard-grey", name: "Longbeard Grey", hex: "#B8B8B8", finish: "MATTE", category: "DRY", range: "Dry" },
      { slug: "necron-compound", name: "Necron Compound", hex: "#A0A8B0", finish: "MATTE", category: "DRY", range: "Dry" },
      { slug: "tyrant-skull", name: "Tyrant Skull", hex: "#D0C898", finish: "MATTE", category: "DRY", range: "Dry" },
      // Dry — additional
      { slug: "astorath-red",         name: "Astorath Red",         hex: "#C84820", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "changeling-pink",       name: "Changeling Pink",       hex: "#E07088", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "chronus-blue",          name: "Chronus Blue",          hex: "#5878C0", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "eldar-flesh",           name: "Eldar Flesh",           hex: "#E0B898", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "etherium-blue",         name: "Etherium Blue",         hex: "#88A8C8", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "golgfag-brown",         name: "Golgfag Brown",         hex: "#A06030", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "golden-griffon",        name: "Golden Griffon",        hex: "#D8A020", finish: "METALLIC", category: "DRY", range: "Dry" },
      { slug: "hexos-palesun",         name: "Hexos Palesun",         hex: "#F0D870", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "imrik-blue",            name: "Imrik Blue",            hex: "#3068B8", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "lucius-the-eternal",    name: "Lucius the Eternal",    hex: "#A0B0C8", finish: "METALLIC", category: "DRY", range: "Dry" },
      { slug: "ryza-rust",             name: "Ryza Rust",             hex: "#C85018", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "sigismund-yellow",      name: "Sigismund Yellow",      hex: "#E8B020", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "stormfang",             name: "Stormfang",             hex: "#5888A8", finish: "MATTE",    category: "DRY", range: "Dry" },
      { slug: "underhive-ash",         name: "Underhive Ash",         hex: "#C0B898", finish: "MATTE",    category: "DRY", range: "Dry" },
      // Contrast — additional (12 → 43 total)
      { slug: "apothecary-white",      name: "Apothecary White",      hex: "#D8DED8", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "aethermatic-blue",      name: "Aethermatic Blue",      hex: "#4A8AC0", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "aggaros-dunes",         name: "Aggaros Dunes",         hex: "#B89050", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "akhelian-green",        name: "Akhelian Green",        hex: "#2A8870", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "basilicanum-grey",      name: "Basilicanum Grey",      hex: "#4A5058", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "celestium-blue",        name: "Celestium Blue",        hex: "#2A5490", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "dark-angels-green",     name: "Dark Angels Green",     hex: "#1A4020", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "death-guard-green",     name: "Death Guard Green",     hex: "#6A8840", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "doomfire-magenta",      name: "Doomfire Magenta",      hex: "#C02878", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "flesh-tearers-red",     name: "Flesh Tearers Red",     hex: "#981020", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "garaghaks-sewer",       name: "Garaghak's Sewer",      hex: "#5A5828", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "grimdark-flesh",        name: "Grimdark Flesh",        hex: "#A06850", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "guilliman-flesh",       name: "Guilliman Flesh",       hex: "#C08870", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "ironjawz-yellow",       name: "Ironjawz Yellow",       hex: "#D08818", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "iyanden-yellow",        name: "Iyanden Yellow",        hex: "#E0A010", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "leviathan-purple",      name: "Leviathan Purple",      hex: "#5A2878", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "leviadon-blue",         name: "Leviadon Blue",         hex: "#1A3060", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "luxion-purple",         name: "Luxion Purple",         hex: "#7A2898", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "magmadroth-flame",      name: "Magmadroth Flame",      hex: "#D04010", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "mantis-warriors-green", name: "Mantis Warriors Green", hex: "#3A7030", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "pylar-glacier",         name: "Pylar Glacier",         hex: "#60A8C0", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "ratling-grime",         name: "Ratling Grime",         hex: "#6A6038", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "shyish-purple",         name: "Shyish Purple",         hex: "#3A1858", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "sigmarite",             name: "Sigmarite",             hex: "#A88028", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "snakebite-leather",     name: "Snakebite Leather",     hex: "#8A5828", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "space-wolves-grey",     name: "Space Wolves Grey",     hex: "#7888A8", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "stonecutters-uniform",  name: "Stonecutters Uniform",  hex: "#808070", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "terradon-turquoise",    name: "Terradon Turquoise",    hex: "#2A9098", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "volupus-pink",          name: "Volupus Pink",          hex: "#D04080", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "warp-lightning",        name: "Warp Lightning",        hex: "#48C830", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      { slug: "wyldwood",              name: "Wyldwood",              hex: "#5A4020", finish: "CONTRAST", category: "CONTRAST", range: "Contrast" },
      // Technical — additional
      { slug: "lahmian-medium",        name: "Lahmian Medium",        hex: "#F0EEE8", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "waystone-green",        name: "Waystone Green",        hex: "#48B870", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "spiritstone-red",       name: "Spiritstone Red",       hex: "#C02020", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "soulstone-blue",        name: "Soulstone Blue",        hex: "#2040C0", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "tesseract-glow",        name: "Tesseract Glow",        hex: "#28C890", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "nurgles-rot",           name: "Nurgle's Rot",          hex: "#689820", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      { slug: "contrast-medium",       name: "Contrast Medium",       hex: "#F0EEE8", finish: "TECHNICAL", category: "TECHNICAL", range: "Technical" },
      // Texture — entire range (new TEXTURE category)
      { slug: "armageddon-dust",       name: "Armageddon Dust",       hex: "#B8A878", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "armageddon-dunes",      name: "Armageddon Dunes",      hex: "#C8A858", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "astrogranite",          name: "Astrogranite",          hex: "#707878", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "astrogranite-debris",   name: "Astrogranite Debris",   hex: "#585858", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "blackfire-earth",       name: "Blackfire Earth",       hex: "#3A2818", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "lustrian-undergrowth",  name: "Lustrian Undergrowth",  hex: "#4A6030", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "martian-ironearth",     name: "Martian Ironearth",     hex: "#904830", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "martian-ironcrust",     name: "Martian Ironcrust",     hex: "#602818", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "mordheim-soil",         name: "Mordheim Soil",         hex: "#4A3828", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "mourn-mountain-snow",   name: "Mourn Mountain Snow",   hex: "#E8EEF0", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "stirland-mud",          name: "Stirland Mud",          hex: "#5A3A18", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "stirland-battlemire",   name: "Stirland Battlemire",   hex: "#3A2010", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      { slug: "valhallan-blizzard",    name: "Valhallan Blizzard",    hex: "#E0E8F0", finish: "TECHNICAL", category: "TEXTURE",   range: "Texture" },
      // Layer — important missing entries
      { slug: "corvus-black",          name: "Corvus Black",          hex: "#202020", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "fenrisian-grey",        name: "Fenrisian Grey",        hex: "#8898B8", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "frostbite",             name: "Frostbite",             hex: "#B8D0E0", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "gauss-blaster-green",   name: "Gauss Blaster Green",   hex: "#70D890", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "warpstone-glow",        name: "Warpstone Glow",        hex: "#389018", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "temple-guard-blue",     name: "Temple Guard Blue",     hex: "#2A9888", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "pink-horror",           name: "Pink Horror",           hex: "#C03870", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "kislev-flesh",          name: "Kislev Flesh",          hex: "#D0A888", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "pallid-wych-flesh",     name: "Pallid Wych Flesh",     hex: "#E8D0BC", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "slaanesh-grey",         name: "Slaanesh Grey",         hex: "#B0A8B8", finish: "MATTE",    category: "LAYER", range: "Layer" },
      { slug: "ironbreaker",           name: "Ironbreaker",           hex: "#9090A8", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "gehenna-gold",          name: "Gehenna's Gold",        hex: "#D8A020", finish: "METALLIC", category: "LAYER", range: "Layer" },
      { slug: "sycorax-bronze",        name: "Sycorax Bronze",        hex: "#B07828", finish: "METALLIC", category: "LAYER", range: "Layer" },
    ],
  },
  {
    slug: "vallejo",
    name: "Vallejo Model Color",
    website: "https://www.acrylicosvallejo.com",
    paints: [
      { slug: "flat-black", name: "Flat Black", hex: "#1A1A1A", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "white", name: "White", hex: "#F5F5F5", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "german-grey", name: "German Grey", hex: "#3A3A3A", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "us-field-drab", name: "US Field Drab", hex: "#7A6840", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "russian-uniform", name: "Russian Uniform", hex: "#5A6840", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "khaki", name: "Khaki", hex: "#C0A860", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "ivory", name: "Ivory", hex: "#F0E8C0", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "basic-skin-tone", name: "Basic Skin Tone", hex: "#D8A880", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "sky-grey", name: "Sky Grey", hex: "#9AB0C0", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "scarlet", name: "Scarlet", hex: "#C01818", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "deep-sky-blue", name: "Deep Sky Blue", hex: "#1868B8", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "medium-sea-grey", name: "Medium Sea Grey", hex: "#688088", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "chocolate-brown", name: "Chocolate Brown", hex: "#502018", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "gold", name: "Gold", hex: "#C8981A", finish: "METALLIC", category: "LAYER", range: "Model Color" },
      { slug: "silver", name: "Silver", hex: "#C0C8D0", finish: "METALLIC", category: "LAYER", range: "Model Color" },
      { slug: "green-ochre", name: "Green Ochre", hex: "#909050", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "buff", name: "Buff", hex: "#D8C098", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "tan-yellow", name: "Tan Yellow", hex: "#C8A048", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "prussian-blue", name: "Prussian Blue", hex: "#0A2040", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "dark-green", name: "Dark Green", hex: "#183818", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "flat-red", name: "Flat Red", hex: "#B01010", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "orange", name: "Orange", hex: "#D86010", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "dark-prussian-blue", name: "Dark Prussian Blue", hex: "#081830", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "pale-sand", name: "Pale Sand", hex: "#E0D0A8", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "yellow", name: "Yellow", hex: "#F0C000", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "medium-grey", name: "Medium Grey", hex: "#808080", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "dark-sea-grey", name: "Dark Sea Grey", hex: "#506870", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "bronze", name: "Bronze", hex: "#A06820", finish: "METALLIC", category: "LAYER", range: "Model Color" },
      { slug: "gunmetal", name: "Gunmetal", hex: "#505870", finish: "METALLIC", category: "BASE", range: "Model Color" },
      { slug: "purple", name: "Purple", hex: "#602878", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "rose", name: "Rose", hex: "#D86080", finish: "MATTE", category: "LAYER", range: "Model Color" },
      { slug: "flat-earth", name: "Flat Earth", hex: "#7A5838", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "oily-steel", name: "Oily Steel", hex: "#6870A0", finish: "METALLIC", category: "LAYER", range: "Model Color" },
      { slug: "dark-rubber", name: "Dark Rubber", hex: "#282828", finish: "MATTE", category: "BASE", range: "Model Color" },
      { slug: "beige-brown", name: "Beige Brown", hex: "#A88058", finish: "MATTE", category: "LAYER", range: "Model Color" },
      // Model Wash (shade/wash range)
      { slug: "black-wash",        name: "Black Wash",        hex: "#181818", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "brown-wash",        name: "Brown Wash",        hex: "#3A2008", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "dark-brown-wash",   name: "Dark Brown Wash",   hex: "#2A1808", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "sepia-wash",        name: "Sepia Wash",        hex: "#7A5020", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "pale-grey-wash",    name: "Pale Grey Wash",    hex: "#C0C8D0", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "light-grey-wash",   name: "Light Grey Wash",   hex: "#A0A8B0", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "sand-wash",         name: "Sand Wash",         hex: "#A09058", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "blue-wash",         name: "Blue Wash",         hex: "#182058", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "green-wash",        name: "Green Wash",        hex: "#1A3818", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      { slug: "red-wash",          name: "Red Wash",          hex: "#601018", finish: "SATIN", category: "SHADE", range: "Model Wash" },
      // Xpress Color (Contrast equivalent)
      { slug: "peacock-green",     name: "Peacock Green",     hex: "#2A8860", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "kobold-skin",       name: "Kobold Skin",       hex: "#A07850", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "burning-sand",      name: "Burning Sand",      hex: "#C09040", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "alien-skin",        name: "Alien Skin",        hex: "#609040", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "gauss-green",       name: "Gauss Green",       hex: "#30C070", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "icy-viking",        name: "Icy Viking",        hex: "#70A8C8", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "moldy-clothes",     name: "Moldy Clothes",     hex: "#7A8840", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "parasite-brown",    name: "Parasite Brown",    hex: "#784020", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "toxic-yellow",      name: "Toxic Yellow",      hex: "#D0D020", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "troll-blood",       name: "Troll Blood",       hex: "#285818", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "berserker-fury",    name: "Berserker Fury",    hex: "#B81020", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "cayman-blue",       name: "Cayman Blue",       hex: "#1A4888", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "gloomy-violet",     name: "Gloomy Violet",     hex: "#502868", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "hot-sunrise",       name: "Hot Sunrise",       hex: "#E08010", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "kraken-skin",       name: "Kraken Skin",       hex: "#2A7870", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
      { slug: "skeleton-bone-xp",  name: "Skeleton Bone",     hex: "#C8A850", finish: "CONTRAST", category: "CONTRAST", range: "Xpress Color" },
    ],
  },
  {
    slug: "vallejo-game-color",
    name: "Vallejo Game Color",
    website: "https://www.acrylicosvallejo.com",
    paints: [
      // Base
      { slug: "black",          name: "Black",          hex: "#100E0E", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "dead-white",     name: "Dead White",     hex: "#F2F2F2", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "heavy-red",      name: "Heavy Red",      hex: "#901818", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "hull-red",       name: "Hull Red",       hex: "#6A2018", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "ultramarine-blue", name: "Ultramarine Blue", hex: "#1A3098", finish: "MATTE", category: "BASE", range: "Game Color" },
      { slug: "night-blue",     name: "Night Blue",     hex: "#182050", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "heavy-blue",     name: "Heavy Blue",     hex: "#1A3080", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "dark-green",     name: "Dark Green",     hex: "#1A4A20", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "cayman-green",   name: "Cayman Green",   hex: "#3A7050", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "goblin-green",   name: "Goblin Green",   hex: "#3A7A2A", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "sombre-grey",    name: "Sombre Grey",    hex: "#504858", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "cold-grey",      name: "Cold Grey",      hex: "#7888A0", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "charred-brown",  name: "Charred Brown",  hex: "#3A2018", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "beastly-brown",  name: "Beastly Brown",  hex: "#604030", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "cavalry-brown",  name: "Cavalry Brown",  hex: "#7A4820", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "leather-brown",  name: "Leather Brown",  hex: "#885030", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "heavy-brown",    name: "Heavy Brown",    hex: "#6A3818", finish: "MATTE", category: "BASE",  range: "Game Color" },
      { slug: "dark-flesh",     name: "Dark Flesh",     hex: "#A05038", finish: "MATTE", category: "BASE",  range: "Game Color" },
      // Layer
      { slug: "bloody-red",     name: "Bloody Red",     hex: "#B01818", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "scarlet-red",    name: "Scarlet Red",    hex: "#D01818", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "orange-fire",    name: "Orange Fire",    hex: "#E87018", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "sun-yellow",     name: "Sun Yellow",     hex: "#F0B810", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "moon-yellow",    name: "Moon Yellow",    hex: "#F0D018", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "scorpy-green",   name: "Scorpy Green",   hex: "#5AB548", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "sick-green",     name: "Sick Green",     hex: "#8CB858", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "jade-green",     name: "Jade Green",     hex: "#307850", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "magic-blue",     name: "Magic Blue",     hex: "#3050B8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "electric-blue",  name: "Electric Blue",  hex: "#2868C8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "glacier-blue",   name: "Glacier Blue",   hex: "#7890B8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "wolf-grey",      name: "Wolf Grey",      hex: "#6888A0", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "ghost-grey",     name: "Ghost Grey",     hex: "#A8B8C8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "fortress-grey",  name: "Fortress Grey",  hex: "#A8B0B8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "bone-white",     name: "Bone White",     hex: "#E0D4B8", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "bonewhite",      name: "Bonewhite",      hex: "#D8C490", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "plague-brown",   name: "Plague Brown",   hex: "#968A54", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "khaki",          name: "Khaki",          hex: "#B8A878", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "dwarf-flesh",    name: "Dwarf Flesh",    hex: "#C87858", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "elf-flesh",      name: "Elf Flesh",      hex: "#E8A878", finish: "MATTE", category: "LAYER", range: "Game Color" },
      { slug: "stonewall-grey", name: "Stonewall Grey", hex: "#889098", finish: "MATTE", category: "LAYER", range: "Game Color" },
      // Game Ink (shades)
      { slug: "black-ink",      name: "Black Ink",      hex: "#181818", finish: "SATIN", category: "SHADE", range: "Game Ink" },
      { slug: "brown-ink",      name: "Brown Ink",      hex: "#3A2010", finish: "SATIN", category: "SHADE", range: "Game Ink" },
      { slug: "red-ink",        name: "Red Ink",        hex: "#681010", finish: "SATIN", category: "SHADE", range: "Game Ink" },
      { slug: "blue-ink",       name: "Blue Ink",       hex: "#182060", finish: "SATIN", category: "SHADE", range: "Game Ink" },
      { slug: "green-ink",      name: "Green Ink",      hex: "#183820", finish: "SATIN", category: "SHADE", range: "Game Ink" },
      // Metallics
      { slug: "polished-gold",  name: "Polished Gold",  hex: "#C89020", finish: "METALLIC", category: "LAYER", range: "Game Color" },
      { slug: "bright-bronze",  name: "Bright Bronze",  hex: "#C07820", finish: "METALLIC", category: "LAYER", range: "Game Color" },
      { slug: "chainmail-silver", name: "Chainmail Silver", hex: "#A8B0C0", finish: "METALLIC", category: "LAYER", range: "Game Color" },
      { slug: "mithril-silver", name: "Mithril Silver", hex: "#C8D0D8", finish: "METALLIC", category: "LAYER", range: "Game Color" },
      { slug: "hammered-copper", name: "Hammered Copper", hex: "#A06030", finish: "METALLIC", category: "LAYER", range: "Game Color" },
      // Game Wash (shade/wash range — distinct from Game Ink)
      { slug: "dark-wash",         name: "Dark Wash",         hex: "#181818", finish: "SATIN", category: "SHADE", range: "Game Wash" },
      { slug: "flesh-wash",        name: "Flesh Wash",        hex: "#9A5028", finish: "SATIN", category: "SHADE", range: "Game Wash" },
      { slug: "green-wash",        name: "Green Wash",        hex: "#183820", finish: "SATIN", category: "SHADE", range: "Game Wash" },
      { slug: "sepia-wash",        name: "Sepia Wash",        hex: "#7A5018", finish: "SATIN", category: "SHADE", range: "Game Wash" },
      { slug: "blue-wash",         name: "Blue Wash",         hex: "#1A2060", finish: "SATIN", category: "SHADE", range: "Game Wash" },
    ],
  },
  {
    slug: "scale75",
    name: "Scale75",
    website: "https://www.scale75.com",
    paints: [
      // Scale Color
      { slug: "inktense-black", name: "Inktense Black", hex: "#0A0808", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "white",          name: "White",          hex: "#F5F5F5", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "red",            name: "Red",            hex: "#B81018", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "alizarin",       name: "Alizarin",       hex: "#A01828", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "crimson",        name: "Crimson",        hex: "#880818", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "orange",         name: "Orange",         hex: "#D07010", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "burnt-orange",   name: "Burnt Orange",   hex: "#C05010", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "yellow",         name: "Yellow",         hex: "#F0C000", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "citrine",        name: "Citrine",        hex: "#D0A820", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "green",          name: "Green",          hex: "#1A8028", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "forest-green",   name: "Forest Green",   hex: "#1A5020", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "dark-sea-green", name: "Dark Sea Green", hex: "#285840", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "emerald",        name: "Emerald",        hex: "#108048", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "jade",           name: "Jade",           hex: "#2A8060", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "blue",           name: "Blue",           hex: "#1830A0", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "cobalt",         name: "Cobalt",         hex: "#1040B0", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "violet",         name: "Violet",         hex: "#601878", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "indigo",         name: "Indigo",         hex: "#180A60", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "brown",          name: "Brown",          hex: "#6A4020", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "chocolate",      name: "Chocolate",      hex: "#3A1A10", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "earth",          name: "Earth",          hex: "#7A5830", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "leather",        name: "Leather",        hex: "#8A5830", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "khaki",          name: "Khaki",          hex: "#808040", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "olive",          name: "Olive",          hex: "#607030", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "grey",           name: "Grey",           hex: "#707070", finish: "MATTE", category: "BASE",  range: "Scale Color" },
      { slug: "silver-grey",    name: "Silver Grey",    hex: "#A0A8B0", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "warm-grey",      name: "Warm Grey",      hex: "#888078", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      { slug: "birch",          name: "Birch",          hex: "#D8C490", finish: "MATTE", category: "LAYER", range: "Scale Color" },
      // Fantasy & Games (skin tones)
      { slug: "skin-shadow",    name: "Skin Shadow",    hex: "#B88060", finish: "MATTE", category: "BASE",  range: "Fantasy & Games" },
      { slug: "skin-mid",       name: "Skin Mid",       hex: "#D0A078", finish: "MATTE", category: "LAYER", range: "Fantasy & Games" },
      { slug: "skin-highlight", name: "Skin Highlight", hex: "#E8C898", finish: "MATTE", category: "LAYER", range: "Fantasy & Games" },
      // Metallurgy (real metal powder pigment)
      { slug: "black-metal",    name: "Black Metal",    hex: "#303038", finish: "METALLIC", category: "BASE",  range: "Metallurgy" },
      { slug: "antique-gold",   name: "Antique Gold",   hex: "#B08018", finish: "METALLIC", category: "LAYER", range: "Metallurgy" },
      { slug: "elven-gold",     name: "Elven Gold",     hex: "#C09020", finish: "METALLIC", category: "LAYER", range: "Metallurgy" },
      { slug: "hammered-silver", name: "Hammered Silver", hex: "#C0C8D0", finish: "METALLIC", category: "LAYER", range: "Metallurgy" },
      { slug: "shining-silver", name: "Shining Silver", hex: "#D0D8E0", finish: "METALLIC", category: "LAYER", range: "Metallurgy" },
      { slug: "bright-copper",  name: "Bright Copper",  hex: "#B87040", finish: "METALLIC", category: "LAYER", range: "Metallurgy" },
      // Scalecolor Ink (transparent inks / washes)
      { slug: "yellow-ink",     name: "Yellow Ink",     hex: "#D0A800", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "orange-ink",     name: "Orange Ink",     hex: "#C05800", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "red-ink",        name: "Red Ink",        hex: "#980810", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "magenta-ink",    name: "Magenta Ink",    hex: "#A0106A", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "violet-ink",     name: "Violet Ink",     hex: "#500A70", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "blue-ink",       name: "Blue Ink",       hex: "#0828A0", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "green-ink",      name: "Green Ink",      hex: "#0A6020", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "brown-ink",      name: "Brown Ink",      hex: "#381008", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      { slug: "black-ink",      name: "Black Ink",      hex: "#080808", finish: "SATIN", category: "SHADE", range: "Scalecolor Ink" },
      // Instant Colors (speed paint / contrast equivalent)
      { slug: "insta-leather",  name: "Insta Leather",  hex: "#8A5030", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-bone",     name: "Insta Bone",     hex: "#C0A060", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-green",    name: "Insta Green",    hex: "#287030", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-blue",     name: "Insta Blue",     hex: "#1A3888", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-red",      name: "Insta Red",      hex: "#980818", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-black",    name: "Insta Black",    hex: "#181818", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-sand",     name: "Insta Sand",     hex: "#C0A860", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
      { slug: "insta-rust",     name: "Insta Rust",     hex: "#904020", finish: "CONTRAST", category: "CONTRAST", range: "Instant Colors" },
    ],
  },
  {
    slug: "pro-acryl",
    name: "Pro Acryl",
    website: "https://monumenthobbies.com",
    paints: [
      { slug: "bold-titanium-white", name: "Bold Titanium White", hex: "#F5F5F5", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-black",     name: "Bold Black",     hex: "#101010", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-red",       name: "Bold Red",       hex: "#C01020", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-magenta",   name: "Bold Magenta",   hex: "#C81870", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-purple",    name: "Bold Purple",    hex: "#7020A0", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-violet",    name: "Bold Violet",    hex: "#401878", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-ultramarine", name: "Bold Ultramarine", hex: "#1830C0", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-cobalt-blue", name: "Bold Cobalt Blue", hex: "#1840A8", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-cyan",      name: "Bold Cyan",      hex: "#00A8C0", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-teal",      name: "Bold Teal",      hex: "#008878", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-green",     name: "Bold Green",     hex: "#1A9830", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-ochre",     name: "Bold Ochre",     hex: "#C89020", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-yellow",    name: "Bold Yellow",    hex: "#F0C000", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "bold-orange",    name: "Bold Orange",    hex: "#D06010", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "brown-black",    name: "Brown Black",    hex: "#1A1008", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "dark-brown",     name: "Dark Brown",     hex: "#4A2010", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "medium-brown",   name: "Medium Brown",   hex: "#7A4820", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "dark-blue-grey", name: "Dark Blue Grey", hex: "#2A3040", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "medium-grey",    name: "Medium Grey",    hex: "#707070", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "light-grey",     name: "Light Grey",     hex: "#B0B8C0", finish: "MATTE", category: "LAYER", range: "Pro Acryl" },
      { slug: "dark-red",       name: "Dark Red",       hex: "#801018", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "dark-green",     name: "Dark Green",     hex: "#1A4018", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "medium-green",   name: "Medium Green",   hex: "#387030", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "skin-tone-1",    name: "Skin Tone 1",    hex: "#A86840", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "skin-tone-2",    name: "Skin Tone 2",    hex: "#C88858", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
      { slug: "skin-tone-3",    name: "Skin Tone 3",    hex: "#D8A870", finish: "MATTE", category: "LAYER", range: "Pro Acryl" },
      { slug: "ivory",          name: "Ivory",          hex: "#EDE0C0", finish: "MATTE", category: "LAYER", range: "Pro Acryl" },
      { slug: "bone",           name: "Bone",           hex: "#D8C898", finish: "MATTE", category: "LAYER", range: "Pro Acryl" },
      { slug: "sand",           name: "Sand",           hex: "#C8B078", finish: "MATTE", category: "LAYER", range: "Pro Acryl" },
      { slug: "dark-purple",    name: "Dark Purple",    hex: "#381058", finish: "MATTE", category: "BASE", range: "Pro Acryl" },
    ],
  },
  {
    slug: "reaper",
    name: "Reaper Miniatures",
    website: "https://www.reapermini.com",
    paints: [
      // Core Colors — organised in triads (shadow / mid / highlight)
      { slug: "pure-black",     name: "Pure Black",     hex: "#0A0A0A", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "pure-white",     name: "Pure White",     hex: "#F5F5F5", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      // Red triad
      { slug: "deep-red",       name: "Deep Red",       hex: "#701010", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "blood-red",      name: "Blood Red",      hex: "#A01818", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "fire-red",       name: "Fire Red",       hex: "#D02020", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Orange triad
      { slug: "harvest-brown",  name: "Harvest Brown",  hex: "#804010", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "orange-brown",   name: "Orange Brown",   hex: "#B06020", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "fire-orange",    name: "Fire Orange",    hex: "#E08030", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Yellow triad
      { slug: "golden-shadow",  name: "Golden Shadow",  hex: "#907020", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "sunlight-yellow", name: "Sunlight Yellow", hex: "#D8B030", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      { slug: "bright-yellow",  name: "Bright Yellow",  hex: "#F0D040", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Green triad
      { slug: "dark-forest-green", name: "Dark Forest Green", hex: "#183818", finish: "MATTE", category: "BASE", range: "Core Colors" },
      { slug: "forest-green",   name: "Forest Green",   hex: "#2A5820", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "leaf-green",     name: "Leaf Green",     hex: "#5A9030", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Blue triad
      { slug: "midnight-blue",  name: "Midnight Blue",  hex: "#0A1840", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "cobalt-blue",    name: "Cobalt Blue",    hex: "#1A3890", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "sapphire-blue",  name: "Sapphire Blue",  hex: "#3060B8", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Purple triad
      { slug: "indigo",         name: "Indigo",         hex: "#280870", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "amethyst-purple", name: "Amethyst Purple", hex: "#5020A0", finish: "MATTE", category: "BASE", range: "Core Colors" },
      { slug: "violet-red",     name: "Violet Red",     hex: "#A01848", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Brown triad
      { slug: "walnut-brown",   name: "Walnut Brown",   hex: "#3A1808", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "chestnut-brown", name: "Chestnut Brown", hex: "#6A3018", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "tanned-leather", name: "Tanned Leather", hex: "#A07040", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Skin triad
      { slug: "dark-skin",      name: "Dark Skin",      hex: "#7A4028", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "tanned-skin",    name: "Tanned Skin",    hex: "#C09060", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "fair-skin",      name: "Fair Skin",      hex: "#D8A878", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Grey triad
      { slug: "blackened-steel", name: "Blackened Steel", hex: "#303038", finish: "MATTE", category: "BASE", range: "Core Colors" },
      { slug: "rainy-grey",     name: "Rainy Grey",     hex: "#7A8890", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "misty-grey",     name: "Misty Grey",     hex: "#B8C0C8", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Bone triad
      { slug: "aged-bone",      name: "Aged Bone",      hex: "#B8A068", finish: "MATTE", category: "BASE",  range: "Core Colors" },
      { slug: "bleached-bone",  name: "Bleached Bone",  hex: "#D8C898", finish: "MATTE", category: "LAYER", range: "Core Colors" },
      // Metallics
      { slug: "honed-steel",    name: "Honed Steel",    hex: "#909AA8", finish: "METALLIC", category: "BASE",  range: "Core Colors" },
      { slug: "polished-silver", name: "Polished Silver", hex: "#C0C8D0", finish: "METALLIC", category: "LAYER", range: "Core Colors" },
      { slug: "antique-gold",   name: "Antique Gold",   hex: "#A88018", finish: "METALLIC", category: "BASE",  range: "Core Colors" },
      { slug: "bright-gold",    name: "Bright Gold",    hex: "#C89820", finish: "METALLIC", category: "LAYER", range: "Core Colors" },
      // Liner (shade/wash)
      { slug: "black-liner",    name: "Black Liner",    hex: "#181818", finish: "SATIN", category: "SHADE", range: "Liner" },
      { slug: "brown-liner",    name: "Brown Liner",    hex: "#2A1808", finish: "SATIN", category: "SHADE", range: "Liner" },
      { slug: "blue-liner",     name: "Blue Liner",     hex: "#102030", finish: "SATIN", category: "SHADE", range: "Liner" },
    ],
  },
  {
    slug: "army-painter",
    name: "Army Painter",
    website: "https://www.thearmypainter.com",
    paints: [
      // Speedpaint 2.0
      { slug: "grim-black", name: "Grim Black", hex: "#181818", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "crusader-skin", name: "Crusader Skin", hex: "#C89068", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "holy-white", name: "Holy White", hex: "#DCDCDC", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "wizard-grey", name: "Wizard Grey", hex: "#707880", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "hardened-leather", name: "Hardened Leather", hex: "#8A5830", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "battleground-brown", name: "Battleground Brown", hex: "#5A3818", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "runic-grey", name: "Runic Grey", hex: "#505860", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "swamp-goblin-green", name: "Swamp Goblin Green", hex: "#3A6030", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "cloudburst-blue", name: "Cloudburst Blue", hex: "#1A3870", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "bony-matter", name: "Bony Matter", hex: "#C8A860", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "burning-corruption", name: "Burning Corruption", hex: "#702010", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      { slug: "slaughter-red", name: "Slaughter Red", hex: "#980818", finish: "CONTRAST", category: "CONTRAST", range: "Speedpaint 2.0" },
      // Warpaints
      { slug: "matt-black", name: "Matt Black", hex: "#1E1E1E", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "pure-red", name: "Pure Red", hex: "#C01010", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "uniform-grey", name: "Uniform Grey", hex: "#606060", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "oak-brown", name: "Oak Brown", hex: "#6A3A18", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "army-green", name: "Army Green", hex: "#386030", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "matt-white", name: "Matt White", hex: "#F0F0F0", finish: "MATTE", category: "BASE", range: "Warpaints" },
      { slug: "dark-tone-ink", name: "Dark Tone Ink", hex: "#242424", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "strong-tone-ink", name: "Strong Tone Ink", hex: "#3A2808", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "soft-tone-ink", name: "Soft Tone Ink", hex: "#9A6020", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "blue-tone-ink", name: "Blue Tone Ink", hex: "#1A2A60", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "green-tone-ink", name: "Green Tone Ink", hex: "#1A3820", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "red-tone-ink", name: "Red Tone Ink", hex: "#601018", finish: "SATIN", category: "SHADE", range: "Warpaints" },
      { slug: "mithril-silver", name: "Mithril Silver", hex: "#C0C8D0", finish: "METALLIC", category: "LAYER", range: "Warpaints" },
      { slug: "shining-silver", name: "Shining Silver", hex: "#D0D8E0", finish: "METALLIC", category: "LAYER", range: "Warpaints" },
      { slug: "weapon-bronze", name: "Weapon Bronze", hex: "#9A6818", finish: "METALLIC", category: "LAYER", range: "Warpaints" },
      { slug: "greedy-gold", name: "Greedy Gold", hex: "#C09010", finish: "METALLIC", category: "LAYER", range: "Warpaints" },
      { slug: "wolf-grey", name: "Wolf Grey", hex: "#8898A8", finish: "MATTE", category: "LAYER", range: "Warpaints" },
      { slug: "skeleton-bone", name: "Skeleton Bone", hex: "#D0C088", finish: "MATTE", category: "LAYER", range: "Warpaints" },
      // Warpaints — additional colours
      { slug: "daemonic-yellow",   name: "Daemonic Yellow",   hex: "#E0A800", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "lava-orange",       name: "Lava Orange",       hex: "#D86010", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "dragon-red",        name: "Dragon Red",        hex: "#B01018", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "barbarian-flesh",   name: "Barbarian Flesh",   hex: "#C08060", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "tanned-flesh",      name: "Tanned Flesh",      hex: "#B87050", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "necrotic-flesh",    name: "Necrotic Flesh",    hex: "#A8B870", finish: "MATTE",    category: "LAYER", range: "Warpaints" },
      { slug: "goblin-green-wp",   name: "Goblin Green",      hex: "#3A7828", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "jade-green-wp",     name: "Jade Green",        hex: "#2A7850", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "crystal-blue",      name: "Crystal Blue",      hex: "#3060A8", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "plasma-blue",       name: "Plasma Blue",       hex: "#20A8D0", finish: "MATTE",    category: "LAYER", range: "Warpaints" },
      { slug: "ash-grey",          name: "Ash Grey",          hex: "#8A9098", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "spaceship-grey",    name: "Spaceship Grey",    hex: "#A0A8B0", finish: "MATTE",    category: "LAYER", range: "Warpaints" },
      { slug: "leather-brown-wp",  name: "Leather Brown",     hex: "#8A5030", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "dirt-spatter",      name: "Dirt Spatter",      hex: "#6A4818", finish: "MATTE",    category: "BASE",  range: "Warpaints" },
      { slug: "purple-wash",       name: "Purple Wash",       hex: "#3A1040", finish: "SATIN",    category: "SHADE", range: "Warpaints" },
    ],
  },
];

// Official cross-brand equivalents (fromSlug => toSlug)
type EquivInput = { from: [string, string]; to: [string, string] };
const OFFICIAL_EQUIVALENTS: EquivInput[] = [
  { from: ["citadel", "abaddon-black"],       to: ["vallejo", "flat-black"] },
  { from: ["citadel", "abaddon-black"],       to: ["army-painter", "matt-black"] },
  { from: ["citadel", "mephiston-red"],       to: ["vallejo", "scarlet"] },
  { from: ["citadel", "mephiston-red"],       to: ["army-painter", "pure-red"] },
  { from: ["citadel", "corax-white"],         to: ["vallejo", "white"] },
  { from: ["citadel", "corax-white"],         to: ["army-painter", "matt-white"] },
  { from: ["citadel", "mechanicus-standard-grey"], to: ["vallejo", "german-grey"] },
  { from: ["citadel", "mechanicus-standard-grey"], to: ["army-painter", "uniform-grey"] },
  { from: ["citadel", "agrax-earthshade"],    to: ["army-painter", "strong-tone-ink"] },
  { from: ["citadel", "nuln-oil"],            to: ["army-painter", "dark-tone-ink"] },
  { from: ["citadel", "reikland-fleshshade"], to: ["army-painter", "soft-tone-ink"] },
  { from: ["citadel", "macragge-blue"],       to: ["vallejo", "prussian-blue"] },
  { from: ["citadel", "retributor-armour"],   to: ["vallejo", "gold"] },
  { from: ["citadel", "retributor-armour"],   to: ["army-painter", "greedy-gold"] },
  { from: ["citadel", "runefang-steel"],      to: ["vallejo", "silver"] },
  { from: ["citadel", "runefang-steel"],      to: ["army-painter", "mithril-silver"] },
  { from: ["citadel", "rhinox-hide"],         to: ["vallejo", "chocolate-brown"] },
  { from: ["citadel", "mournfang-brown"],     to: ["vallejo", "flat-earth"] },
  { from: ["citadel", "zandri-dust"],         to: ["vallejo", "buff"] },
  { from: ["citadel", "averland-sunset"],     to: ["vallejo", "yellow"] },
  { from: ["citadel", "caliban-green"],       to: ["vallejo", "dark-green"] },
  { from: ["citadel", "naggaroth-night"],     to: ["vallejo", "purple"] },
  { from: ["citadel", "dawnstone"],          to: ["vallejo", "medium-grey"] },
  { from: ["citadel", "screaming-skull"],     to: ["vallejo", "ivory"] },
  { from: ["citadel", "ushabti-bone"],        to: ["vallejo", "pale-sand"] },

  // Citadel → Vallejo Game Color
  { from: ["citadel", "abaddon-black"],       to: ["vallejo-game-color", "black"] },
  { from: ["citadel", "corax-white"],         to: ["vallejo-game-color", "dead-white"] },
  { from: ["citadel", "mephiston-red"],       to: ["vallejo-game-color", "heavy-red"] },
  { from: ["citadel", "macragge-blue"],       to: ["vallejo-game-color", "ultramarine-blue"] },
  { from: ["citadel", "caliban-green"],       to: ["vallejo-game-color", "dark-green"] },
  { from: ["citadel", "mechanicus-standard-grey"], to: ["vallejo-game-color", "sombre-grey"] },
  { from: ["citadel", "rhinox-hide"],         to: ["vallejo-game-color", "beastly-brown"] },
  { from: ["citadel", "mournfang-brown"],     to: ["vallejo-game-color", "cavalry-brown"] },
  { from: ["citadel", "retributor-armour"],   to: ["vallejo-game-color", "polished-gold"] },
  { from: ["citadel", "runefang-steel"],      to: ["vallejo-game-color", "mithril-silver"] },
  { from: ["citadel", "naggaroth-night"],     to: ["vallejo-game-color", "night-blue"] },
  { from: ["citadel", "nuln-oil"],            to: ["vallejo-game-color", "black-ink"] },
  { from: ["citadel", "agrax-earthshade"],    to: ["vallejo-game-color", "brown-ink"] },
  { from: ["citadel", "drakenhof-nightshade"], to: ["vallejo-game-color", "blue-ink"] },
  { from: ["citadel", "biel-tan-green"],      to: ["vallejo-game-color", "green-ink"] },

  // Citadel → Scale75
  { from: ["citadel", "abaddon-black"],       to: ["scale75", "inktense-black"] },
  { from: ["citadel", "corax-white"],         to: ["scale75", "white"] },
  { from: ["citadel", "mephiston-red"],       to: ["scale75", "red"] },
  { from: ["citadel", "macragge-blue"],       to: ["scale75", "cobalt"] },
  { from: ["citadel", "caliban-green"],       to: ["scale75", "forest-green"] },
  { from: ["citadel", "naggaroth-night"],     to: ["scale75", "violet"] },
  { from: ["citadel", "kantor-blue"],         to: ["scale75", "indigo"] },
  { from: ["citadel", "retributor-armour"],   to: ["scale75", "elven-gold"] },
  { from: ["citadel", "runefang-steel"],      to: ["scale75", "shining-silver"] },
  { from: ["citadel", "zandri-dust"],         to: ["scale75", "khaki"] },
  { from: ["citadel", "rhinox-hide"],         to: ["scale75", "chocolate"] },
  { from: ["citadel", "steel-legion-drab"],   to: ["scale75", "earth"] },
  { from: ["citadel", "death-world-forest"],  to: ["scale75", "olive"] },

  // Citadel → Pro Acryl
  { from: ["citadel", "abaddon-black"],       to: ["pro-acryl", "bold-black"] },
  { from: ["citadel", "corax-white"],         to: ["pro-acryl", "bold-titanium-white"] },
  { from: ["citadel", "mephiston-red"],       to: ["pro-acryl", "bold-red"] },
  { from: ["citadel", "macragge-blue"],       to: ["pro-acryl", "bold-ultramarine"] },
  { from: ["citadel", "caliban-green"],       to: ["pro-acryl", "dark-green"] },
  { from: ["citadel", "naggaroth-night"],     to: ["pro-acryl", "dark-purple"] },
  { from: ["citadel", "mechanicus-standard-grey"], to: ["pro-acryl", "medium-grey"] },
  { from: ["citadel", "zandri-dust"],         to: ["pro-acryl", "sand"] },
  { from: ["citadel", "rhinox-hide"],         to: ["pro-acryl", "dark-brown"] },
  { from: ["citadel", "averland-sunset"],     to: ["pro-acryl", "bold-ochre"] },
  { from: ["citadel", "jokaero-orange"],      to: ["pro-acryl", "bold-orange"] },
  { from: ["citadel", "screaming-skull"],     to: ["pro-acryl", "bone"] },

  // Citadel → Reaper
  { from: ["citadel", "abaddon-black"],       to: ["reaper", "pure-black"] },
  { from: ["citadel", "corax-white"],         to: ["reaper", "pure-white"] },
  { from: ["citadel", "mephiston-red"],       to: ["reaper", "blood-red"] },
  { from: ["citadel", "macragge-blue"],       to: ["reaper", "cobalt-blue"] },
  { from: ["citadel", "caliban-green"],       to: ["reaper", "forest-green"] },
  { from: ["citadel", "averland-sunset"],     to: ["reaper", "sunlight-yellow"] },
  { from: ["citadel", "rhinox-hide"],         to: ["reaper", "chestnut-brown"] },
  { from: ["citadel", "mournfang-brown"],     to: ["reaper", "walnut-brown"] },
  { from: ["citadel", "retributor-armour"],   to: ["reaper", "bright-gold"] },
  { from: ["citadel", "runefang-steel"],      to: ["reaper", "polished-silver"] },
  { from: ["citadel", "mechanicus-standard-grey"], to: ["reaper", "rainy-grey"] },
  { from: ["citadel", "naggaroth-night"],     to: ["reaper", "amethyst-purple"] },
  { from: ["citadel", "nuln-oil"],            to: ["reaper", "black-liner"] },
  { from: ["citadel", "agrax-earthshade"],    to: ["reaper", "brown-liner"] },
  { from: ["citadel", "screaming-skull"],     to: ["reaper", "bleached-bone"] },
  { from: ["citadel", "ushabti-bone"],        to: ["reaper", "aged-bone"] },
  { from: ["citadel", "zandri-dust"],         to: ["reaper", "tanned-leather"] },
  { from: ["citadel", "bugmans-glow"],        to: ["reaper", "dark-skin"] },
];

export async function seedPaints(prisma: PrismaClient) {
  console.log("  Seeding paint brands and paints...");

  const brandIdMap = new Map<string, string>();

  // 1. Upsert brands sequentially (only 7, fast)
  for (const brand of BRANDS) {
    const b = await prisma.paintBrand.upsert({
      where: { slug: brand.slug },
      update: { name: brand.name, website: brand.website },
      create: { slug: brand.slug, name: brand.name, website: brand.website },
    });
    brandIdMap.set(brand.slug, b.id);
  }

  // 2. Bulk-insert all paints per brand using createMany (one query per brand)
  for (const brand of BRANDS) {
    const brandId = brandIdMap.get(brand.slug)!;
    const data = brand.paints.map((paint) => {
      const lab = hexToLab(paint.hex);
      return {
        brandId,
        slug: paint.slug,
        name: paint.name,
        hex: paint.hex,
        finish: paint.finish,
        category: paint.category,
        range: paint.range,
        labL: lab.L,
        labA: lab.a,
        labB: lab.b,
      };
    });
    await prisma.paint.createMany({ data, skipDuplicates: true });
    console.log(`    ✓ ${brand.name} (${brand.paints.length} paints)`);
  }

  // 3. Resolve all equivalent paint IDs in parallel, then bulk-insert
  console.log("  Seeding official paint equivalents...");
  const { deltaE2000: dE } = await import("../../lib/paint-hub/color");

  const resolved = await Promise.all(
    OFFICIAL_EQUIVALENTS.map(async (eq) => {
      const fromBrandId = brandIdMap.get(eq.from[0]);
      const toBrandId   = brandIdMap.get(eq.to[0]);
      if (!fromBrandId || !toBrandId) return null;

      const [fromPaint, toPaint] = await Promise.all([
        prisma.paint.findUnique({ where: { brandId_slug: { brandId: fromBrandId, slug: eq.from[1] } } }),
        prisma.paint.findUnique({ where: { brandId_slug: { brandId: toBrandId,   slug: eq.to[1]   } } }),
      ]);
      if (!fromPaint || !toPaint) return null;

      return {
        fromPaintId: fromPaint.id,
        toPaintId:   toPaint.id,
        deltaE: dE(
          { L: fromPaint.labL, a: fromPaint.labA, b: fromPaint.labB },
          { L: toPaint.labL,   a: toPaint.labA,   b: toPaint.labB   },
        ),
        isOfficial: true,
      };
    }),
  );

  const equivData = resolved.filter((r): r is NonNullable<typeof r> => r !== null);
  await prisma.paintEquivalent.createMany({ data: equivData, skipDuplicates: true });
  console.log(`    ✓ ${equivData.length} official equivalents seeded`);
}
